clear; close all; clc

%% directories

cdir = pwd;
odir = ('output');
fdir = ('figures');

%% load data

save_graph = 1;

cd(odir)
shocks_DATA  = readtable('shocks.csv','Delimiter',',');
quarter = table2array(shocks_DATA(:,1));
news    = table2array(shocks_DATA(:,2)); news = 100*news;
ind     = table2array(shocks_DATA(:,3)); ind(1) = ind(2);
bp      = table2array(shocks_DATA(:,4));

cd(cdir)

% quarter  = DATA_GRAPH(:,1);
% IND      = DATA_GRAPH(:,2); 
% NEWS_LAG = DATA_GRAPH(:,3); 
% BPq = DATA_GRAPH(:,6);

%messi
%% Plot


fig = figure('units','normalized','outerposition',[0 0 1 1]); % figure

% Define RGP color codes (gray is not standard so need RGB) and set them
right_color      = 0.4*[1 1 1]; %./255; % red
left_color     = [0.5 0.4 .1];%./255; % blue
shaded_color    = [0 0 255] ./ 255;% blue [1 0 0]; %; 
backg_color     = [0 0 1]; % red
set(fig,'defaultAxesColorOrder',[left_color; right_color]); % color for axes

% Set axes 
xlim([min(quarter) max(quarter)])
% Make x axis cross both y axes at zero
y_low_lhs = -75/3; %min(NEWS_LAG) - nanmean(NEWS_LAG);
y_upp_lhs = 75; %max(NEWS_LAG) + nanmean(NEWS_LAG);
ratio_lhs = abs(y_upp_lhs/y_low_lhs);
y_low_rhs = -0.33;%.2/3; %min(BPq) - nanmean(BPq);
y_upp_rhs = ratio_lhs*abs(y_low_rhs);

[AX,H1,H2] = plotyy(quarter,news,quarter,bp); %,'LineWidth',1.5)
set(H2,'linestyle','-.','color',right_color','LineWidth',3)%,'Xtick',[0,4,8,12],'Xticklabels',{'0','1',');
set(H1,'color',left_color,'LineWidth',3)

set(AX(1),'ylim',[y_low_lhs y_upp_lhs],'xlim',[1913 2006.75],'Fontsize',27,... )%,'ylabel','News (Ramey)','Interpreter','Latex');
'Ytick',[-25 0 25 50 75],'Yticklabels',{'-0.25','0','0.25','0.50', '0.75'});

set(AX(2),'ylim',[y_low_rhs y_upp_rhs],'xlim',[1913 2006.75],'Fontsize',27,...
    'Ytick',[-25 0 25 50 75-0.00001]/25*.33,'Yticklabels',{'-0.07','0','0.07','0.13','0.20'});

ylabel(AX(1), 'Shocks: $RZ$','Fontsize',27,'Interpreter','Latex');
ylabel(AX(2), 'Shocks: $BP$','Fontsize',27,'Interpreter','Latex');
set(gca,'XGrid','on','YGrid','on','Fontsize',27,'TickLabelInterpreter', 'LaTex')  

%title('Spending shocks and states','Fontsize',24)
%set(gca, 'Color', 'None')%, gcf, 'Color', 'None')

%azeazeaze
%%


hold on

% Add overlay of shaded areas (MUST BE BETTER WAY TO DO THIS)
% IND=1
IND_1 = {2:27; 54:61; 74:94; 102:129; 145:159; 173:176; 182:196; 214:228; 234:262; ...
    309:329; 334:351; 377};
% IND=0
IND_0 = {1; 28:53; 62:73; 95:101; 130:144; 160:172; 177:181; 197:213; 229:233;...
    263:308; 330:333; 352:376; 378:400};

% Make blue part 
for k1 = 1:size(IND_1,1)
    q = IND_1{k1};
    if length(q) == quarter(1)
        q = [q q+1];
    end
    qx = [quarter(min(q)-1) quarter(max(q)+1)  quarter(max(q)+1)  quarter(min(q)-1)];
    yl = ylim;
    qy = [[1 1]*(yl(1)+0.1) [1 1]*(yl(2)-0.1)];
    patch(qx, qy, shaded_color,'FaceAlpha',0.1,'EdgeColor','w')
end


uistack(H1,'top')
uistack(H2)

% % Make red part (Note: Background color affects all colors - this does not)
% for k2 = 1:size(IND_0,1)
%     q = IND_0{k2};
%     if length(q) == quarter(1)
%         q = [q q+1];
%     end
%     qx = [quarter(min(q)) quarter(max(q))  quarter(max(q))  quarter(min(q))];
%     yl = ylim;
%     qy = [[1 1]*yl(1) [1 1]*yl(2)];
%     patch(qx, qy, backg_color,'FaceAlpha',0.25)
% end

%%% Wilson reforms 
annotation(fig,'textbox',...
    [0.12 0.77 0.091 0.05],...
    'String',{'Wilson','TRA 1916/17/18'},...
    'LineStyle','none',...
    'HorizontalAlignment','center',...
    'FontSize',17,...
    'FitBoxToText','off','Interpreter','Latex');

%%% Andrew Mellon
annotation(fig,'textbox',...
    [0.16 0.7 0.098 0.05],...
    'String',{'Mellon','TRA 1921/24/26/28'},...
    'LineStyle','none',...
    'HorizontalAlignment','center',...
    'FontSize',17,...
    'FitBoxToText','off','Interpreter','Latex');

%%% Roosevelt + Hoover
annotation(fig,'textbox',...
    [0.26 0.81 0.15 0.069],...
    'String',{'Roosevelt','TRA 1935/36/40/41/42/43/44'},...
    'LineStyle','none',...
    'HorizontalAlignment','center',...
    'FontSize',17,...
    'FitBoxToText','off','Interpreter','Latex');

annotation(fig,'textbox',[0.27625 0.695157384987893 0.06 0.08],...
    'String',{'Hoover','TRA 1932'},...
    'LineStyle','none',...
    'FontSize',17,...
    'FitBoxToText','off','Interpreter','Latex');


%%% Truman
annotation(fig,'textbox',...
    [0.35 0.71 0.11 0.08],...
    'String',{'Truman','TRA 1945/48'},...
    'LineStyle','none',...
    'HorizontalAlignment','center',...
    'FontSize',17,...
    'FitBoxToText','off','Interpreter','Latex');

%%% Korea
annotation(fig,'textbox',...
    [0.37 0.82 0.18 0.08],...
    'String',{'Korea','TRA 1950/51/54'},...
    'LineStyle','none',...
    'HorizontalAlignment','center',...
    'FontSize',17,...
    'FitBoxToText','off','Interpreter','Latex');

%%% Kennedy-Johnson
annotation(fig,'textbox',...
    [0.51 0.815 0.10 0.07],...
    'String',['Kennedy-Johnson',sprintf('\n'),'TRA 1964'],...
    'LineStyle','none',...
    'HorizontalAlignment','center',...
    'FontSize',17,...
    'FitBoxToText','off','Interpreter','Latex');

%%% 70s
annotation(fig,'textbox',[0.57 0.72 0.15 0.08],...
    'String',{'Increased deductions','TRA 1971/75/76','+ bracket creeping'},...
    'LineStyle','none',...
    'HorizontalAlignment','center',...
    'FontSize',17,...
    'FitBoxToText','off','Interpreter','Latex');

%%% Reagan
annotation(fig,'textbox',...
    [0.67 0.81 0.09 0.08],...
    'String',{'Reagan','ERTC 1981','TRA 1986'},...
    'LineStyle','none',...
    'HorizontalAlignment','center',...
    'FontSize',17,...
    'FitBoxToText','off','Interpreter','Latex');

%%% Bush+Clinton
annotation(fig,'textbox',...
    [0.75 0.74 0.12 0.09],...
    'String',['Bush + Clinton',sprintf('\n'),'OBRA 1990/93/97'],...
    'LineStyle','none',...
    'HorizontalAlignment','center',...
    'FontSize',17,...
    'FitBoxToText','off','Interpreter','Latex');

%%% Bush Jr
annotation(fig,'textbox',...
    [0.83 0.62 0.085 0.07],...
    'String',{'Bush','EGTRRA 2001'},...
    'LineStyle','none',...
    'HorizontalAlignment','center',...
    'FontSize',17,...
    'FitBoxToText','off','Interpreter','Latex');

hold off

% figure('units','normalized','outerposition',[0 0 1 1])

% Labels
xlabel('Year','Fontsize',27,'Interpreter','Latex')

fig = gcf;
fig.PaperUnits = 'inches';
fig.PaperPosition = [0 0 22 11];
if (save_graph == 1 )
    cd(fdir)
    print('FIGURE_13','-dpng','-r0')
    cd(cdir)
end